# Generated by Django 2.2.4 on 2021-10-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20211015_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='head_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
