# Generated by Django 2.2.4 on 2021-10-25 12:25

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20211020_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
